### ISSUE TITLE
"python3 setup.py test" does not run the tests

### ISSUE THREAD

**Issue by drexlerd** [rleap-project/dlplan#13]

**Comment by jendrikseipp** [comment]
I think this way of calling tests is deprecated. I recommend using "tox". See Lab or Fast Downward for examples.

**Comment by gfrances** [comment]
Hey guys, at the moment you can run the tests by simply calling pytest on
the appropriate directory, but definitely that needs to be documented.
We can add a top-level tox.ini config file too, I didn't want to pollute
too much the root folder unless you're ok with it :-)

Missatge de Jendrik Seipp ***@***.***> del dia dv., 11 de
juny 2021 a les 10:45:

**Comment by drexlerd** [comment]
added testing with tox
