### ISSUE TITLE
Setters to toggle feature generation, verbosity

### ISSUE THREAD

**Issue by drexlerd** [rleap-project/dlplan#33]
Replace feature generator's default arguments and replace them with setters. Additionally have one setter for verbositty.

**Comment by drexlerd** [comment]
I added this functionality. However, Javi suggested generalizing the implementation by having a single setter, i.e., set_enabled(std::string identifier, bool enabled), or maybe use an enum instead. I like this idea but want to hear more opinions before changing this again.

**Comment by jendrikseipp** [comment]
I like the current implementation better. Strings are brittle. The current implementation will not compile when a name is misspelled (which is helpful) and it also allows IDEs to autocomplete.
