### ISSUE TITLE
Use -Werror in GitHub Actions

### ISSUE THREAD

**Issue by jendrikseipp** [rleap-project/dlplan#34]
I think it would be good to use the -Werror flag to turn compilation warnings into errors, but only for automated tests in GitHub Actions. (We don't want to break compilation for users simply because we compare an int to a size_t.) This can be achieved by running

    export CXXFLAGS="-Werror" # Treat compilation warnings as errors.

in `unittests.yml` before building dlplan.

**Comment by drexlerd** [comment]
I added this line. I would have expected the compilation to fail because I never really cared about fixing those warnings but it didn't. Maybe it didn't work?

**Comment by jendrikseipp** [comment]
Probably you need to export the value in the same step as the cmake command.

**Comment by drexlerd** [comment]
done.
