### ISSUE TITLE
Enable multi core feature generation

### ISSUE THREAD

**Issue by drexlerd** [rleap-project/dlplan#39]

**Comment by drexlerd** [comment]
Current thread-pooling idea:

Main thread: For each iteration i: 
  (1) compile tasks where each task is the construction of a single feature with complexity i. These tasks are added to a thread-safe queue Q. 
  (2) solve tasks until Q is empty and proceed with the next iteration.

Worker threads:
  (1) solve tasks until Q is empty

**Comment by jendrikseipp** [comment]
Sounds good to me :-)

**Comment by drexlerd** [comment]
Current design works in principle but is nondeterministic because each worker adds the result.

To fix this, the worker should only compute the element + the hash value of the denotation.
The main thread must add the elements to the result.

**Comment by drexlerd** [comment]
[report.zip](https://github.com/rleap-project/dlplan/files/7899631/report.zip)
memory usage seems to be quite large when using multi-core because it runs out of memory even with 48GB available on 16 cores or I am using the experimental framework incorrectly.
216196 total generated elements until complexity 10 does not seem too much.

**Comment by drexlerd** [comment]
The error was caused by Fast Downward Lab (FDL). It looks like FDL uses the process CPU-time to measure elapsed time which corresponds to the sum of computation spend across all threads in the process. We now scale the timeout with the number of threads which roughly mimics the wanted behavior.
The latest experiments show best performance when using 8 threads.
[report.zip](https://github.com/rleap-project/dlplan/files/7918095/report.zip)

**Comment by jendrikseipp** [comment]
Nice! I added this to the Lab docs.
