### ISSUE TITLE
Use lock-free datastructures for caching the elements

### ISSUE THREAD

**Issue by drexlerd** [rleap-project/dlplan#42]
This feature is not planned in the near future but will allow further scaling when increasing the number of threads. Please share implementations if you find any.

Here is some discussion: https://stackoverflow.com/questions/14338732/is-it-possible-to-implement-lock-free-map-in-c

**Comment by jendrikseipp** [comment]
https://github.com/greg7mdp/parallel-hashmap looks interesting for this.

**Comment by drexlerd** [comment]
Thanks, Jendrik! I quickly tested it on the example instance and it already increased performance by 30% on 4 cores. I will rerun benchmarks to see performance there.
