### ISSUE TITLE
State space component?

### ISSUE THREAD

**Issue by drexlerd** [rleap-project/dlplan#50]
After looking at the data that Simon posted in discord, there is quite a lot of gain from integrating state space pruning in the context of description logics features. Additionally, Daniel mentioned pruning strategies on the task level that we can implement in the scorpion submodule. Maybe also integrate functionality to read the output from scorpion state space exploration into DLPlan. I think there is quite some useful things to do on this level that makes a lot of sense to implement these things efficiently and reusable.

**Comment by jendrikseipp** [comment]
I agree that this sounds like an interesting direction.

As I understand it, Simon's pruning also works on the task level and not on the DL features level.

**Comment by drexlerd** [comment]
done.
