### ISSUE TITLE
Some math on caching in the feature generator

### ISSUE THREAD

**Issue by drexlerd** [rleap-project/dlplan#51]
Here is a calculation of how much memory we might need to cache all denotations during feature generation.

Assumptions: bitset representation for `core::State`, `core::ConceptDenotation`, and `core::RoleDenotation`, 10^4 states [s], 10^2 atoms [a], 10^2 objects [o], 10^5 [c] novel `core::Concept` and 10^5 [r] `core::Role` in total. These numbers are reasonable upper bounds to what we might want to scale up. We want to cache all denotations. Then

space required to store states: 10^4 [s] * 10^2 [a] is negligible
space required to store concept denotations: 10^4 [s] * 10^2 [o] * 10^5 [f] Bits = 10^11 Bits is roughly 12.5 GB
space required to store role denotations: 10^4 [s] * (10^2 [o])^2 * 10^5 [f] Bits = 10^13 Bits 1250 GB 

Caching the concept denotations is not a problem at least but caching role denotations is a problem.

Some of the assumed numbers might be larger than what we usually expect so on a cluster with roughly 400 GB of available memory on a node I expect that caching everything can work if we do not fragment the memory.

Alternative 1: set a limit on the memory size of denotation caches and kick out elements with some criteria, e.g., not retrieved frequently enough. I think this is a bit too experimental and we can do better with Alternative 2.
Alternative 2: cache only for a single state and pass 1 state and all concepts and roles with complexity c in current iteration to be evaluated in a thread, this drops the factor of 10^4 [s] and we get 125 MB * <#threads> required memory for role denotations. It is a reasonable approach because the number of concepts and roles with complexity c is much larger (?) than the number of novel concepts and roles with complexity <c, e.g., for the binary concept c_and we consider all pairs of concepts with complexity <c such that resulting c_and has complexity c. That is quadratic growth (?) while we only have to compute linearly many denotations of novel concepts and roles with complexity <c.

Let me know what you think. With (?) I marked places where I am still unsure.

**Comment by jendrikseipp** [comment]
Nice analysis! I agree that Alternative 2 sounds reasonable. Maybe it would be good to dump some numbers during a typical feature generation to see whether the parts with question marks hold in practice.

**Comment by jsego** [comment]
I think is good to set a limit on the memory size, since there is always a physical memory limit. Maybe update this limit depending on how much is available in the workstation and play with that amount. If you decide to go for "Alternative 1", I suggest to look into ["cache algorithms"](https://simple.wikipedia.org/wiki/Cache_algorithm#:~:text=The%20most%20efficient%20caching%20algorithm,algorithm%20or%20the%20clairvoyant%20algorithm.) that essentially decide what should be removed when not everything fits in memory.

Regarding the (?)s, the number of features looks like a [worst-case quadratic function](https://stackoverflow.com/questions/4632322/finding-all-possible-combinations-of-numbers-to-reach-a-given-sum), where for each new concept/role at most *two features* of the previous iteration will be joined. Note that in general is $O(n^m)$ where $m$ is the max number of features to join out of $n$ that add up to $k-1$ complexity, but that can be solved in $O(2^n)$ (look at the previous link). So #features of complexity k can be potentially much larger than the sum of all previous features with complexity k' < k, being the case of joining at most two features the simplest one.

What I don't fully get is the comment: `...while we only have to compute linearly many denotations of novel concepts and roles with complexity <c`. It is computing concepts/roles *linearly* an aim, a fact, an intuition...

**Comment by drexlerd** [comment]
@jsego Thanks for explanations and pointers. That's good and as Jendrik suggested I will print out additional statistic to see how many evaluations we can save with this strategy.

> What I don't fully get is the comment: ...while we only have to compute linearly many denotations of novel concepts and roles with complexity <c. It is computing concepts/roles linearly an aim, a fact, an intuition...

What I mean by that is given we are in current iteration c and we have n concepts and roles with complexity <c. Then since we consider a new state to evaluate all new concepts and roles with complexity c, we have to evaluate each of the n concepts exactly once. The fraction between newly generated concepts and roles with complexity =c and novel concepts and roles with complexity <c gives a rough estimate of gain from this strategy, i.e., quadratic / linear yields roughly linearly many cache retrievals per cache entry computation.

**Comment by drexlerd** [comment]
I started implementing caching everything for a first try because we usually have only very few roles anyways. Just some todos so that I don't forget.

After each iteration i, we obtain a fragmented indexing of elements because some elements are pruned, hence we must:
1. remap indices of novel elements in iteration i to non-fragmented indexing, 
2. set start index for newly created index in the element cache to the number of elements in the cache.
3. copy cached denotations of elements in cache to the position of their new index
4. mark remaining position in the denotation cache with indices greater of equal than number of elements in the cache as uncached such that newly created elements will be evaluated and not point to denotations of previous iterations.

**Comment by drexlerd** [comment]
New implementation based on the one in D2L without bloom filter, so no false positives are pruned. We provide three methods to evaluate elements: (1) single state without cache (as baseline), (2) single state with cache (when set of states in unknown in advance, e.g., during state space search), and (3) multiple states with cache (used in feature generator when states are given as input). For a Delivery instance with 96 states we now need 1s and 31mb to compute features to complexity 15 :) 

[t=1.05131s, 31020 KB] Complexity 15:
Total concept elements: 2182
Total role elements: 9
Total numerical elements: 2326
Total boolean elements: 121
    b_nullary: 0
    c_one_of: 0
    c_top: 1
    c_bot: 1
    c_primitive: 5
    r_primitive: 5
    c_and: 959
    c_not: 661
    c_projection: 5
    c_equal: 2
    c_some: 287
    c_all: 261
    r_restrict: 0
    r_inverse: 3
    r_transitive_closure: 1
    b_empty: 121
    n_count: 1650
    n_concept_distance: 676
[t=1.05142s, 31020 KB] Finished generating composite features.
Started element evaluation
Number of boolean elements: 121
Number of numerical elements: 2326
Number of states: 96
Number of evaluations per element: 1000
Time evaluate features for single state without cache: 266391ms
Time evaluate features for single state with cache: 84489ms
Time evaluate features for all states with cache: 75ms

**Comment by jendrikseipp** [comment]
Impressive! What was the runtime and memory usage before this change?

btw: I don't understand the last three log lines above. How is evaluating all states with a cache faster than evaluating a single state with a cache?
